# QUARKUS APP ENVIRONMENT
environment: |-
  QUARKUS_LOG_CONSOLE_JSON: "false"
  QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgresql:5432/quarkusdb
  MP_JWT_VERIFY_PUBLICKEY_LOCATION: https://keycloak:8080/realms/quarkus/protocol/openid-connect/certs
  MP_JWT_VERIFY_ISSUER: https://keycloak:8080/realms/quarkus
  APP_AUTHORIZATION_ENABLED: "false"

# SEALED SECRETS: https://github.com/bitnami-labs/sealed-secrets
# echo -n app-secret-value | kubeseal --raw --from-file=/dev/stdin --name application
# echo -n liquibase-secret-value | kubeseal --raw --from-file=/dev/stdin --name liquibase
# ---
secrets:
  app:
    dbUsername: AgAomceJo5GuMWSv2ZCrpYlyvPPpKafKaws1qZoM1lwxLLCHGDHCUukrQka6206u0lbJCN7kgGRmY6n2dtKwR3rmadhleFKaiUDmYGsWz29iak/M2OpnvOjBwa+R8vUCPodDF7KaKrkgaST4+QwEeYuLCUDeuxgccQrWmOSRxKZNQM41UN9tDAhDhGZa7ggTkBp9pSyZQyvr4uWgUcKRvkjvDAN3BZTirv2HZnmDpZ1Kmsm4tO1soqF+dTb2MookwY0nHL4nPSiLRhxQu9bhHk0DYAXg9pEDzK602CQphth1CMq5lk/GE1dRmh1AWK1Yzlki0ULgmdZgRYOhlexnTfVt71KE88UXR3z0dwUcD717G/K0ZeHbrUFtqfENMZMSyAqZK9XacdE/i9LuVIcBhkdx8MGzD53CmiR6nWjDYs8dWg9Zj8wEBplDUsg2t7PzHwLFIgp+VR5udXndRoUgtSr8Htm29apC66iOORpBz86XMFPASRGd+7jnUjAlMDi9Y9mb8zfC4zBtlzR/kEoSPChZHWORYJ4soIMtfZ4o5EPGQZP6C/hDmPzCVhlmnfrFQGj9GyJCrL4mAmjawv/m78sW/j/I6j6qV74tTg5IQFNZNwhfzAnDsbfnG0+DsBU8+v1Oxd4pVOGu2CH6jayJrXrH7FwFfCd7ik9IofnUnv3EzxJ0GCHNjI1uce0/ogPzpvu/SWQi1NjK
    dbPassword: AgAUIGy+LQSTDixCPIsPwzQ6BAUk7xDnPJUdLHncmJ+s3rR5K41nBDBYHT3x3nki47KLId0DJnEwbqjiDI+CWGjnzDJ8UKMZBHt2ADL5CVIMmKOf3eOiBI9vDKECbIUXQExuW234b4+uySdDAnYRHFEPWa/Cz6LrKQPDUMAX3zPI1C17ccsVcBQio1AOmCh+g9mKWGxmiz3JeKd2qns/ae2RNLoJ8YqiHUuNcYt7F+9jMJrKnplZVy3rQ029JuevidTl5QQOlaQskxhKkE3edoQS//dWExvNtXsP9rUrQ59fNGs7G+e4GVfuQL8T+LWeUhdW3q2r8lmSESXyajTl8s7gQglye9Tl9Jt1KS5ZxCH5j0ePgNfu98limu2UHIKoMw3qcVSZ8MIoQ5ehVQgQlMRSLxIacGuniJIAdKFsU4UAIY9y6hlMUYVpV/rBJcUvz74LHaLKM2v5rJcpfkYydrip2btqQRKLTsl5yUdODHV5MaaA2J7uvvAXcNWCBBgvaMrtrAtBGLykbGvSdM2QYkUfLpE9K0+tMvQB534BVU+Zbp7D+pTZezDztp+LCtnvBwdOxZcfX8hzK9IQ6zkoVWtZGPT0AhEnCHmqW33xKGy4XHqi7W2Vx2J1yIo6EmZPXlSmpM2vK1BsDpYQYcZNPq5Goqj9LkB6XonsocYKkzQnI5vkbqJX3M4Y5iyxitXqTatEZgqWIyuVmg==
  liquibase:
    dbUsername: AgAomceJo5GuMWSv2ZCrpYlyvPPpKafKaws1qZoM1lwxLLCHGDHCUukrQka6206u0lbJCN7kgGRmY6n2dtKwR3rmadhleFKaiUDmYGsWz29iak/M2OpnvOjBwa+R8vUCPodDF7KaKrkgaST4+QwEeYuLCUDeuxgccQrWmOSRxKZNQM41UN9tDAhDhGZa7ggTkBp9pSyZQyvr4uWgUcKRvkjvDAN3BZTirv2HZnmDpZ1Kmsm4tO1soqF+dTb2MookwY0nHL4nPSiLRhxQu9bhHk0DYAXg9pEDzK602CQphth1CMq5lk/GE1dRmh1AWK1Yzlki0ULgmdZgRYOhlexnTfVt71KE88UXR3z0dwUcD717G/K0ZeHbrUFtqfENMZMSyAqZK9XacdE/i9LuVIcBhkdx8MGzD53CmiR6nWjDYs8dWg9Zj8wEBplDUsg2t7PzHwLFIgp+VR5udXndRoUgtSr8Htm29apC66iOORpBz86XMFPASRGd+7jnUjAlMDi9Y9mb8zfC4zBtlzR/kEoSPChZHWORYJ4soIMtfZ4o5EPGQZP6C/hDmPzCVhlmnfrFQGj9GyJCrL4mAmjawv/m78sW/j/I6j6qV74tTg5IQFNZNwhfzAnDsbfnG0+DsBU8+v1Oxd4pVOGu2CH6jayJrXrH7FwFfCd7ik9IofnUnv3EzxJ0GCHNjI1uce0/ogPzpvu/SWQi1NjK
    dbPassword: AgAUIGy+LQSTDixCPIsPwzQ6BAUk7xDnPJUdLHncmJ+s3rR5K41nBDBYHT3x3nki47KLId0DJnEwbqjiDI+CWGjnzDJ8UKMZBHt2ADL5CVIMmKOf3eOiBI9vDKECbIUXQExuW234b4+uySdDAnYRHFEPWa/Cz6LrKQPDUMAX3zPI1C17ccsVcBQio1AOmCh+g9mKWGxmiz3JeKd2qns/ae2RNLoJ8YqiHUuNcYt7F+9jMJrKnplZVy3rQ029JuevidTl5QQOlaQskxhKkE3edoQS//dWExvNtXsP9rUrQ59fNGs7G+e4GVfuQL8T+LWeUhdW3q2r8lmSESXyajTl8s7gQglye9Tl9Jt1KS5ZxCH5j0ePgNfu98limu2UHIKoMw3qcVSZ8MIoQ5ehVQgQlMRSLxIacGuniJIAdKFsU4UAIY9y6hlMUYVpV/rBJcUvz74LHaLKM2v5rJcpfkYydrip2btqQRKLTsl5yUdODHV5MaaA2J7uvvAXcNWCBBgvaMrtrAtBGLykbGvSdM2QYkUfLpE9K0+tMvQB534BVU+Zbp7D+pTZezDztp+LCtnvBwdOxZcfX8hzK9IQ6zkoVWtZGPT0AhEnCHmqW33xKGy4XHqi7W2Vx2J1yIo6EmZPXlSmpM2vK1BsDpYQYcZNPq5Goqj9LkB6XonsocYKkzQnI5vkbqJX3M4Y5iyxitXqTatEZgqWIyuVmg==

# Requests and limits for the app pod deployment
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# HPA autoscaling
autoscaling:
  enabled: true
  minReplicas: 2
