# QUARKUS APP environment
environment: |-
  QUARKUS_LOG_CONSOLE_JSON: "false"
  QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgresql:5432/quarkusdb
  MP_JWT_VERIFY_PUBLICKEY_LOCATION: https://keycloak:8080/auth/realms/quarkus/protocol/openid-connect/certs
  MP_JWT_VERIFY_ISSUER: https://keycloak:8080/auth/realms/quarkus
  APP_AUTHORIZATION_ENABLED: "false"

# SEALED SECRETS: https://github.com/bitnami-labs/sealed-secrets
# echo -n app-secret-value | kubeseal --raw --from-file=/dev/stdin --name application
# echo -n liquibase-secret-value | kubeseal --raw --from-file=/dev/stdin --name liquibase
# ---
secrets:
  app:
    dbUsername: AgC9ArBT85pH/ZZtQY+TfRioz2ZUr90bevvgVGiPQp+aaNBWZPgPMwi7CENjQdLYTPlp8xNrmZa1ce0CTaY34m55m3aE/Oa2nrcT6uNQfnLRMVOz9Z+3iim2weQJ8DKUs0AZiFAIehFkYQRIi+hBCT1QtmMiLkhy48ekvFnNS4kX96eFPktaHIqFwu2C5D+La8ZBZRMGPulQzdVHC6Xx13MbdVkRymgKt95aAbxK2qSTjEmJDX2ng3dv4FHAnC4N7pztuJ3b1kaq2S5Zo/XnQzaDiVQ5JpWqCYQG5ZKl0QuW+Kl2mx666di1zEJoJnRV9LbkuggP+quBkTfGGYaOOGu+TzLJRNGMJujmjVjRxQ9L8uV36nKfGDNMpfvycgW8XytVB18vqCyn9qMA7gRqwS7IrNw+CLiXeiTxPLkEk6F8WN1/oMcRo6p+U6mwwxsmRJiIYD6bRkYP4d6EDjdzaxduhaddJebSCsmyUbivbaHH0dijYLi7DiW07i0kompPvIS1JNjxaFVK+IqGEBv5xTPcwflDMhleJcU2PF7kp72Bgizzq5oTBwbeugnP27a27O2gQ1ilAaIS+s78lK/JNTvurYVlxdrGi8AJm+eeMeO+CFPE8xofB0Ii4QYDrQyEMHi/0tG6D/btMK2T3nKBkNKpDyCUz7ieLoZDd9dIVSGQof7rzp2P4qXEzV4puvDT2ieegmrABBaI
    dbPassword: AgDLMXTn3CKo29R3hO9nsibWJVTPazM974HsDIfxuPmBihZGNZj1K6djo14lIw3ZmWfUvdY7/veHuxJUPCPT2l/jcP0S3n1NFHNUXKo2xKFS0ws6HgOlWQXZwyntQARGGX0QAvXwecWn65TwAEXfhXra5V3Tqx0za7y02G7ryZ54Iw6RX5XeW9np6kBvob9zdmT/1P+X4+ih0ZUYLh9jPm5gfTVzBJfgHW+3uGhZASTnAqbkgGhU1W/gJYWpv85cO7yzSjjj3Md+c9EoFe2H6Php9PKNjSUKWoUWriNGY0TQvHfDKh+pYV9ZiT/+O6AQppCCQHwXPk6VdZSXz3m+IN0ENwSLeAr6B7k4IfnJNrV8lPzVak/U7RDF6KcMVp+fI9u0q/pn5isEC04f92khFxIOmNGveADl8++oVGXHurmn3tRyzFgPJqgmmXJ775etVkNhXpjKZglEcPODg1+h0WRwVQscjD7Ci6xmIOcwka831x9gcmam0OVkp6LEGS0xUVo5Fn7q9Zqi9mkLY2RLlpy+9aaGvbf90jNrn2o+q/goEJSVcKhklOb2R/S5OQA2xjP6kuqjdf7VAcP7tUoeJDIPxbKcYktjNNed8xrchwEKt2rGu13F/mMWA6x2jVLOoqAA1ihPE+jBcGLCMV00DUHUvu9Y/ycvD182ESC3fEerWH9xhRsvJgG0wNlDftciodGSb0QZSdn9tA==
  liquibase:
    dbUsername: AgC0HoRhZeHp2dhn8KxERXpReQ3+HeH0pTFk2/T+Tb5v1cz5UBI+SlTbCk1qbATbwIKm4gh9dspGtH0NornRpJj4azItfAGvTxoWw7P5Dyz72uDGyV2GZpGfjZ0NR7vNWdJzl7rr1qJqYsdNktePjCN3OvJQVrkPFziWNhrRMNUUN5F5YxGu3LmKOaFiJdPt59AnxxcWe/2xRgK5JfGYsAJSJciihuXUkYBWKl8V1u1urrgI7E/xC2rhXgB6YlsLsCowGK0oovF6dBMrxYFj6yknET0cwwb4I3iUBT0LbIPJM8Bj2rlMPFOEdMZHAnIIzfMt06tOJ81gvOdYTVZM339eKZo02AvDsYJFiCIPt1lPGD8Iuo3In3Fh/7fojPcE0FSHdZZCWnw9CSPaFlUznB1n/P5M7Gepj6hAPYIHyK8U9WuthSlidLRGE7RmiqiLVmrVMOveQtvJyxselF5fCch/xuDAGrL4f3KrZYTpJngmxF9rSjO1WprFjPkY00gIJYxZo0wBjM1Xsk3KxJ1thn/WU1h4OMd+plOK13cam8HuMqpitSq/dRMR6b4C8LRrzbJdWg8Vdt1mgnIXWDCjVGN+lgRxeYnrv/PJ8YgZK4ZO9N/sY1O2S4g40yq1pvH/Fg2KhOJGYFJFBEpX+sTD+5/oBLbItpmtjhPde60dXYwTcyyqzyMx7M0O3fYX5+5cVG9RyMrzOre1
    dbPassword: AgCdwDsIVjLqQy/11z7AqsDGHPdT/7M5zRrJYAnniFQevgGuDPYpbYEF0b9JxeTSLcoAIYyV/nkl5PbVvJ8SUxn6OIPLXzBXrIHouCzVYnaOx0D5WbLNQy6uYAP3pIymHW0jaOzuVhO85ng9+vxjowebTYwGP1o6apVqzdjpCuPk1ZXwTsUs3y4Ist4xHYEJlCvr0K2Nb/2rYzzwMfd3jF/Snha+BcU0qiqHE6Nr9r59g2huushD+SUqVWsbrQYTiLan6fvPHtZNVzXlu3sJbSO3SLHu87ixOWiIIHw2K/Fn+lUA4/qTH+6Dg/5yBb5Fmk4H9K0jiWgaqldFg6n+2SXNBPZsUOdJra5sx3hs+/ytyDXROSOpJYQ/Sr5TkPtstfuYTxp84c997UrtbEI+YRAoQzyxf1u7yT8aGOVK7Yb/Yz6PHl/sOMJWaOU13p/Uuu6lxL0ki48pU8WUzNsfmKXP3gFlijSQiPvR3RVAabJqW/wl6bwWx1dTZn6iC/5X7IInVw8hb0CEFijdcHSMwV2H3PEHmCn98dp/jZvYytUBNl5GfEY1cgkYd2KCnESUwxip08qKYivP7c6dKF7H9ylT8LrKU8HqO87J8fA/lCoIUCObtvCk4193AJbw5NdU3CPhoBzMggR2PwvaF7ZwvNnhsQRphBKUW2QsyBTLWjtuMCfhecbZJuKoGUATtvOAHfQ7cqq8CEPSLg==

# todo
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
