# QUARKUS APP ENVIRONMENT
environment: |-
  QUARKUS_LOG_CONSOLE_JSON: "false"
  QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgresql:5432/quarkusdb
  MP_JWT_VERIFY_PUBLICKEY_LOCATION: https://keycloak:8080/auth/realms/quarkus/protocol/openid-connect/certs
  MP_JWT_VERIFY_ISSUER: https://keycloak:8080/auth/realms/quarkus
  APP_AUTHORIZATION_ENABLED: "false"

# SEALED SECRETS: https://github.com/bitnami-labs/sealed-secrets
# echo -n app-secret-value | kubeseal --raw --from-file=/dev/stdin --name application
# echo -n liquibase-secret-value | kubeseal --raw --from-file=/dev/stdin --name liquibase
# ---
secrets:
  app:
    dbUsername: AgApcHeCQiI3b8N2/sk8vYZjfhMo8RpDAD4ktNNI5zymeIQrNX7po5Uu+p9zdbyfqHn2SpD1pdknw4o2LzyVFWdy/hR25vhW19xDrGj7MpOOJ2lmvV0PW1aSNL8v7AXhWC49zxeLiR5nwBov7gMEU9qjl7d82hXVTlvoRLA7wPhRoALCwotmzymw9l5SzLHiCL7Jb0ytKdYE4lZuKBvBkfiPo15AHT7oZn+dxz48qf+uPqRyK++MNsMiixqLkCIUdAvrW6rOSw8OlxkX5gEvHg5gB1eS7HZnaqhnuYn1chCzhGSjd47Ct1MOX1Vw4hw39GifN3gIbkfp28tv0JUtGKMFvwX06F/U+u9tYlXS1yYvIsLHeyA05EicjhNr0FzrYPLiiUhNLlkSqiw/C5MWBmgxHgsdFaoiTLcm30eru8o4CFkZwMGpw6ncGgp/6hY6orZPi7MDA8g4t/e5UIr+s4YBoWLXyiQ6eN0AYD74V9WpbLklsObpUniHrxF7XZd3ytc3uU7O5HukKFNrCWvcAtJh9x/JLxRCl0dnOAO7bwqotUWPaULePyNpVrcG6am0RsHa5RBsQZsmH3dE4s4cq00nAJhWQd0u8fAB7wYnCYUfdGVi48hJZVbtGDktDd2sgAy5m/61YvR11Yhq6B+Ob13f6Bbe2drXm1js6RAq3oP0eapcVrIqvymnN9trGT5xnQA5ij5TTLMp
    dbPassword: AgBxfriaqMw/YAuOYdcSl64sPwjFw5XnsOmIhbF21pqFsc3LCFKFPpoGj5QvxU9Mb9NzceDJCkV8LfJ4MdJRFNkfcAMvwrP/2EvbCikNXg4kaXoXMg7DPqBo7zO9lgj7A97ejuODswfth+Y4fuuHSWDoTJLLcuFxfUddkfrStlSydl6Du/GL9JIWGtLn0A1F6RvYMo8JChfj+7O5vMBn2JVyDCradN6OmDDNr83LUbuKV+J4oybtBEQXHcJCZLKCSHvW6EY3KY+mb/o1OVJbyPglArAll04UKO76SEGMoTfo9Mb7Xn8jXrN/I5JF8ymmmDoUlS3W+tf0IJdz0xbifk2OkATT87XMzs2m/Esjn+F5Dzr6ggU9LmliAfBV19Lfck8WBMEj1aWMbcFnTiK5XAc+JTHbKKaxNisxDlI7ZZMGfysLKthcdI2dno5tcarXtythbLC/RjaNQb+uxglEgbESER5nsC6jB58j+mE5D5MXOsnXMTfbHXlgtvEkRX9IXuZIUhGnl01IWkDeIfohjJdDEftZcDyvTS8nQYXLZKwf9tUWA8edNRy4dSi/03a6XloxW4Q83wnOHjhVJLXTGiUt1SrR5vmjr3yRDz+LUxlwaULQ3o0YiyCY0rDVu4hCAn7IvOL6Vk1RaicFnGZ4JBauGOIvC1EeyY76xACo8rRRN3V9Z5D1Y0qAt5Dx3r/VguCVkYTPS9zrug==
  liquibase:
    dbUsername: AgB68AHgKvHgw1luzhGm5DUB72m/sh3Qwl5LwbQCD8YX5a7dJ7rz0TikXV/uE7KJDcu3JXIdp/O/27F3T/gbyramu2iJSEIT2oLEBaumOtHz8Og61X4bcbpfN+ceH+93r9jS8sma8Hp4968tq1yjX14xw1Z6Kxs5Oaw4SwNFTQfQvvvyMfijNqwy68Ks78dnRWfMiorWY25IDso/YLKNtvGkMC8iIERaI+OsALCSw1GcOgfSw+HVS4e3+RmSSL+mbKhE6ZhDMw4fCkf/YBdrqHl3iiwolhEFqNcTW4XDibn8rh74T0culA5RJswz9u4NvNL8LzlXNjX7+6nhudRcWrdKG46xEMUH20bas0z9hJAVswg8aKgCb8h/9C0bPaN5lq98CkQIidt7LDr9lc2yuXbCix/fg0TgxVY42EeenJwHuQXcwTWgBgteB1rv//0LlV6kqvT8TPEYFWpxOB2mr+S4Jsz9zzk1lfdpjbf/H3nwF1ZNwoQaofdvceeNQ4eg/vyPJdNwcvuH3YiVRM7QVcGR5M7VnMBsRzPiWl8YrJpFJdVQgoRkB9Ql0GZjDRaN2W6mylHVe725kYXtRvkVsfJa0tw0w8z6IW+RcsjN0+H6yB5cEzzc8kwVpElitqyV1O8tL6p7xdgDbxDEiEIxlTUG9szlnmPnF25eEhyz+2bDzMheHu5e5LeZyjD4ar8ihXtjWw+DULt0
    dbPassword: AgBvdBGob8FQYAmyOXv3r9Av9TWqf7qt/DQFfVMX5BPPEyzufk9nYVOMFzC0Mr2YEPwKrE2fNoJWyYOnzRUjR1/tjhmJ2nQrVkFOvtK876vx4zrapDPqU580lvjmFF0X47Aq4MtOjcBTpu8ebqnVsbWEBOQPhbm4MEqIHbESpsKsu/wWzT8lxpctjxeP8oCr924nyEDkUebx6/63jzMTNCJDaUMDm5/YFo+mft5mxrzyEysrthvC/qLHJ6hMrtFSdduBFrjhjeu+k2JwideVs61q7IJR/ykvk6/9JdLooOHE4NLkamlE5bHukwpjn05CUBQNRPP9aEVlI/JztlICVXXDHX495CM+PlkGqPCOWepltmtLijnOxmCKUPz2UsWP826jYG8kEusqlrdrsFQKIlHv3epnm0hd0TwQc15lTg5eHp5VRN7I3xm7M6ipxFJ7Uj1rJRBcBwyBxkdZ31r7+RZ6sfYDvg59k6Rn838idqx6kvqL18HEbq/LVtLmxi8/gSso7ndwkvxRGaWYlx1+yHMm42v1s7pAhV8eBArZWso5tHhyus0M6Qso04sK43v3akUkRPRZJQhYcnojvxQeHXVFLC0bg+K0pRSmCILA3bVBfac6mAbZIh5NjDkPsI66qVmtMMQ5IbcbqpWDfUMeFv2U0MW1uiS8PtCHBWJiM50FXl6B3VKpwpjBxKfOoXwHbMN0irf8i5yolA==

# Requests and limits for the app pod deployment
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# HPA autoscaling
autoscaling:
  enabled: true
  minReplicas: 2
